### ISSUE TITLE
Add section explaining for MDAKits hackathon

### ISSUE THREAD

**Issue by fiona-naughton** [MDAnalysis/UGM2023#11]
Add a section to the Hackathon MDAKit details outlining where/how attendees can express interest or discuss one of our suggested projects (to be added in #4 ), or propose their own.

As discussed at the last MDAKits meeting, the current plan is to create a separate issue for each projects to the start of the UGM for each MDAKit, and folks can discuss there.

**Comment by orbeckst** [comment]
I am copying my suggestion from Discord to here:

Having a clear playbook might help, along the lines of

## Before hackathon

1.    read materials, watch intro videos
2.    make sure you have a GitHub account
3.    use Discord ⁠hackathon (see #17 ) to talk to other participants in advance. Let people know if you're interested in working together on anything specific.
4.    If you have a specific project in mind, raise an issue in the UGM issue tracker https://github.com/MDAnalysis/UGM2023/issues with title `[project] short description`. Post a link to the issue in Discord.
5.    Or: look at posts and issues and start a conversation there on anything that interests you. Having questions on issues themselves helps focusing the discussion and easily makes them available for all other contributors lately. (That's what we do in MDAnalysis development.)


## At hackathon

1.    talk to other attendees
2.    look at issues, discord, and through talking to find something to work on
3.    form groups (or work on a project yourself)
4.    raise an issue for a project that you're working on — this provides a quick overview over all activity and makes it easy for us to help in a specific manner (including developers who may be remote)
5.    hack away, build something awesome, make new friends, have fun!

**Comment by IAlibay** [comment]
@fiona-naughton is this complete now?
