### ISSUE TITLE
add links for Discord #hackathon channel

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/UGM2023#17]
A the link for the Discord `#hackathon` channel https://discord.com/channels/807348386012987462/1152628719354118205

Include the link for joining our Discord: ~~https://discord.gg/fXTSfDJyxE~~ EDIT: see https://github.com/MDAnalysis/UGM2023/issues/17#issuecomment-1722425248 below.

- [x] top level hackathon README
- [x] MDAkits README
- [x] Blender README (?)

**Comment by jennaswa** [comment]
This is the Discord invite link we were going to provide in the logistics email to send people directly to the UGM 2023 category: https://discord.com/invite/sAKgZZnPv4
