### ISSUE TITLE
Make individual issues for proposed Hackathon Projects

### ISSUE THREAD

**Issue by fiona-naughton** [MDAnalysis/UGM2023#21]
Holding off on making these just yet to avoid cluttering the UGM issue tracker, but to be ready for when Hackathon details are sent to participants on Monday 25th.

- [x] One Issue per proposed MDAKit project. Title/details to be copied from the existing [project list](https://github.com/MDAnalysis/UGM2023/blob/main/hackathon/mdakits/projects.md#project-ideas-for-mdakits-hackathon)
- [ ] Add a link to issue in the project list

**Comment by IAlibay** [comment]
I decided to go ahead and open the issues - if we're contacting folks tomorow they should be open by the time they read the email.
