### ISSUE TITLE
list of hackathon MDAKit projects

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/UGM2023#4]
Based on https://docs.google.com/document/d/14D1wpiytpJ4CYrLNz33lWEw-wNL6Ny83jewP3BJY1Bo/edit
- one big list (instead of ~one markdown file per project in hackathon section #3~ )
- content similar to GSOC project outline
- include relevant academic references, links to other code
- links to relevant issues

**Comment by fiona-naughton** [comment]
Per discussion this week, I believe the current plan is to consolidate the potential projects into one list, and open separate issues for each closer to the date to allow people to sign up/discuss

**Comment by orbeckst** [comment]
I think we have our initial list. @fiona-naughton , as you have been looking after these aspects of the hackathon, can you please close unless in your view there's still stuff to do? If the latter, which issues are open and relevant?
